# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rak' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rak
   pod 'Parse'
   pod 'ParseUI'
   pod 'AFNetworking'
   pod 'BDBOAuth1Manager'

  target 'rakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
